#Primeira aula prática - Video 04 (Curso em vídeo)

''' *Apague aqui para funcionar o código*


print ("Hello World") # Forma básica para impressão na tela
print (2+5) # Imprime apenas o resultado da operação
print ('2'+'5') # Uni apenas não soma
print ('Olá','5') # Nesse caso usa-se a virgula por se tratar da união de frase com números.

# Variáveis -> é utilizada para guardar informação(nome, numeros)

nome = 'Philippe'
idade = 29
peso = 82.0



print (nome, idade, peso)
print ('Meu nome é:',nome) # Neste caso usa-se o (+) ou (,)
print('Minha idade é:', idade)

*Apague aqui para funcionar o código* '''


# FUNÇÃO INPUT -> É UTILIZADA PARA ATRIBUIR VALORES A UMA VARIÁVEL

'''
nome = input ('qual é seu nome? ')
idade = input ('qual é sua idade? ')


print ('minha idade é:' + idade)
print ('memeu nome é:' +nome)

'''



#Tips


# Toda variável é um objeto e objetos são mais que variáveis
# toda variável recebe valores (=) Significa Receber
# Nome = 'Guamabara', Lê-se: nome recebe guanabara
# Utilizar sempre letras minúsculas 


#DESAFIOS

# 1) CRIE UM SCRIPT PYTHON QUE LEIA O NOME DE UMA PESSOA E MOSTRE UMA MENSAGEM DE BOAS-VINDAS DE ACORDO COM O VALOR DIGITADO.

'''
desafio1 = input ("Seja bem vindo, vai começar o desafio")

nome = input (" Qual é seu nome? ")
print ("Olá "+ nome +" é um Prazer te conhecer!, você passou no desafio 1, Passe para próxima etapa.")

Enter = input ('Aperte ENTER para avançar.')

'''
# 2) CRIE UM SCRIPT PYTHON QUE LEIA O DIA, O MÊS E O ANO DE NASCIMENTO DE UMA PESSOA E MOSTRTE UMA MENSAGEM COM A DATA FORMATADA.

'''
desafio2 = input ("Desafio 2: Leia a questão no código e crie o script.")

dia = input('Que dia é hoje ? ')
mes = input('Em que mês estamos? ')
ano = input('De qual ano? ')

Resposta = input

print('Estamos no ano de ' + ano + ' no dia ' + dia + ' do mês de ' + mes +'.')

'''
# 3) CRIE UM SCRIPT PYTHON QUE LEIA DOIS NÚMEROS E TENTE MOSTRAR A SOMA ENTRE ELES. 

'''

n1 = int(input ('Digite o primeiro valor: '))
n2 = int(input ('Digite o segundo valor: '))
soma = n1+n2

print ('A soma dos valores é: ' , soma , '.')
'''

# DESAFIOS 1,2 E 3 CONCLUÍDOS. 31/05/2022