#FUNÇÃO FORMAT ('xyz'.format(x,x,x))

n1 = int(input('digite o primeiro valor: '))
n2 = int(input('digite o segundo valor: '))
soma = n1+n2

print('a soma entre {} e {} é {}' .format(n1, n2, soma))

# A FUNÇÃO FORMAT CHAMA AS VARIÁVEIS PARA DENTRO DOS PARENTESIS.
# A FUNÇÃO FORMAT SERVE PARA DIMINUIR A QUANTIDADE DE ASPAS E VIRGULA EM UMA SENTENÇA.
# A QUANTIDADE DE COLCHETES DEVE SEGUIR A MESMA QUANTIDADE DE ITENS DENTRO DOS PARENTESIS APÓS A FUNÇÃO FORMAT.
# A SEQUENCIA DEVE SER RESPEITADA
