# MVT -
# MODEL
# VIEW: RECEBE UMA REQUISIÇÃO E DEVOLVE UMA RESPOSTA
# TEMPLATE: ARQUIVO TEXTO

#DLT = DJANGO TEMPLATE LENGUAGE

# ATAQUES
# INJEÇÃO SQL , CROSS SITE SCRIPTING (XSS), CROSS SITE REQUEST FORGEY(CSRF) CLICKJACKING